//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbClientes
    {
        public string cedula { get; set; }
        public int tipoCliente { get; set; }
        public int descMax { get; set; }
        public byte[] foto { get; set; }
    
        public virtual tbPersona tbPersona { get; set; }
        public virtual tbTipoClientes tbTipoClientes { get; set; }
    }
}
