//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarios
    {
        public string cedula { get; set; }
        public int idRol { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string contrasena { get; set; }
        public bool estado { get; set; }
    
        public virtual tbPersona tbPersona { get; set; }
        public virtual tbRoles tbRoles { get; set; }
    }
}
